// Generated by CoffeeScript 1.4.0
(function() {

  Object.prototype.mixin = function(Klass) {
    var key, value, _ref;
    for (key in Klass) {
      value = Klass[key];
      this[key] = value;
    }
    _ref = Klass.prototype;
    for (key in _ref) {
      value = _ref[key];
      this.prototype[key] = value;
    }
    return this;
  };

  /*
  class Mixie
    @repeat: (thing) -> thing
    @create: (attrs) -> "created"
    save: -> "saved it"
    sing: -> "lalallala"
  
  class User
    @mixin Mixie
  
  alert User.repeat(1)
  
  aUser = new User
  alert aUser.sing()
  */


}).call(this);
